# Generated by Django 4.2.11 on 2024-06-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.IntegerField()),
                ('row', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
