# Generated by Django 4.2.11 on 2024-06-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_api', '0002_seat_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('seat_id', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
