# Generated by Django 4.2.11 on 2024-06-19 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning_api', '0001_initial'),
        ('ticket_api', '0003_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='seat_id',
        ),
        migrations.AddField(
            model_name='ticket',
            name='planning',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='planning_api.planning'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticket_api.seat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
